site_name: Spatium Documentation
site_description: Network Configuration Analyzer and Digital Twin Platform
site_author: Spatium Team
repo_url: https://github.com/t0m3kz/spatium
repo_name: spatium

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [spatium]
  #         options:
  #           show_source: true
  #           docstring_style: google

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Device Configuration: user-guide/device-config.md
    - Configuration Analysis: user-guide/config-analysis.md
    - Digital Twins: user-guide/digital-twins.md