name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      
      - name: Install tools
        run: |
          pip install uv
          uv venv
          uv sync 
      
      - name: Lint & Format
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run yamllint -d "{extends: default, ignore: [.github/]}" \
                -d "{rules: {truthy: {allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']}}}" .

  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: lint-and-format
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          uv sync 
      
      - name: Run tests
        run: uv run pytest tests --cov=src --cov-report=xml
      
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: matrix.python-version == '3.10'
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 5

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e ".[dev]"
      
      - name: Build docs
        run: mkdocs build
      
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/
          retention-days: 5
